apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values: [node3]
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "lcj/lvm"
      fsType: "ext4"
      options:
        volumeID: "LogVol00"
        size: "1000m"
        volumegroup: "VolGroup00"
